### ISSUE TITLE
Homebrew error

### ISSUE THREAD

**Issue by drewauff** [GGP1/kure#15]

**Comment by drewauff** [comment]
`Error: kure: /usr/local/Homebrew/Library/Taps/ggp1/homebrew-tap/Formula/kure.rb:1: syntax error, unexpected <<
<<<<<<< Updated upstream
^~
/usr/local/Homebrew/Library/Taps/ggp1/homebrew-tap/Formula/kure.rb:58: syntax error, unexpected ===, expecting end-of-input
=======
^~~
`

**Comment by GGP1** [comment]
I've found that many people with a Mac M1 had the same issue in projects using GoReleaser. My guess is that the script that it generates is not recognizing the M1 as an arm CPU and fails because of that.

Here:

```rb
on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/GGP1/kure/releases/download/v0.4.7/kure_v0.4.7_macOS_ARM64.tar.gz"
      sha256 "b36fa8fa0c98adc8e986fd5e202c2e4f91ecc9915cfd6e9c8650759d7fee6222"

      def install
        bin.install "kure"
      end
    end
...
```
The logged error is confusing since there are no syntax errors in the file. I'm not sure if the issue is from GoReleaser or is that the Ruby version used does not recognizes M1s in `Hardware::CPU.arm?`.

You can dowloand the pre-compiled binary `kure_v0.4.7_macOS_ARM64.tar.gz` from [releases](https://github.com/GGP1/kure/releases/tag/v0.4.7) until the bug is fixed.

**Comment by drewauff** [comment]
probably should noted, Im on an intel Mac running Catalina if that makes a difference...

**Comment by drewauff** [comment]
Decided I'd uninstall it for now, unfortunately same error......
